version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: parking-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parking-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: parking-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    networks:
      - parking-network

  mongo:
    image: mongo:6.0
    container_name: parking-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db
    networks:
      - parking-network

networks:
  parking-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: